typeset -g ZDOTDIR="${ZDOTDIR:-$HOME/.config/zsh}"
source "$ZDOTDIR/environment.zsh"
source "$ZDOTDIR/base.zsh"
source "$ZDOTDIR/completion.zsh"
source "$ZDOTDIR/function.zsh"
source "$ZDOTDIR/alias.zsh"
source "$ZDOTDIR/bindkey.zsh"
source "$ZDOTDIR/plugins.zsh"
source "$ZDOTDIR/external_tool_init.zsh"
